# Generated by Django 5.2.5 on 2025-09-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('xero', 'Xero')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('auth_url_template', models.URLField()),
                ('token_url', models.URLField()),
                ('revoke_url', models.URLField(blank=True, null=True)),
                ('scopes_default', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
