# Generated by Django 5.2.5 on 2025-09-04 03:22

from django.db import migrations


def copy_integration_providers(apps, schema_editor):
    """Copy data from integrations.IntegrationProvider to connections.Provider"""
    # Get model classes from migrations
    IntegrationProvider = apps.get_model('integrations', 'IntegrationProvider')
    Provider = apps.get_model('connections', 'Provider')
    
    # Copy all IntegrationProvider records to Provider
    for old_provider in IntegrationProvider.objects.all():
        Provider.objects.create(
            name=old_provider.name,
            display_name=old_provider.display_name,
            provider_type=old_provider.provider_type,
            is_active=old_provider.is_active,
            auth_url_template=old_provider.auth_url_template,
            token_url=old_provider.token_url,
            revoke_url=old_provider.revoke_url,
            scopes_default=old_provider.scopes_default,
            created_at=old_provider.created_at,
            updated_at=old_provider.updated_at,
        )
    
    print(f"Copied {IntegrationProvider.objects.count()} providers to connections.Provider")


def reverse_copy_integration_providers(apps, schema_editor):
    """Reverse operation - delete all Provider records"""
    Provider = apps.get_model('connections', 'Provider')
    count = Provider.objects.count()
    Provider.objects.all().delete()
    print(f"Deleted {count} providers from connections.Provider")


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('integrations', '__latest__'),  # Ensure integrations migrations are applied
    ]

    operations = [
        migrations.RunPython(
            copy_integration_providers,
            reverse_copy_integration_providers,
        ),
    ]
