# Generated by Django 5.2.5 on 2025-09-04 03:36

import django.db.models.deletion
import shared.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20250904_0322'),
        ('core', '0002_add_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(max_length=255)),
                ('external_account_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Authorization'), ('active', 'Active'), ('expired', 'Token Expired'), ('revoked', 'Access Revoked'), ('error', 'Error State')], default='pending', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.provider')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('account', 'provider', 'external_account_id')},
            },
            bases=(models.Model, shared.models.PrefixIdMixin),
        ),
    ]
