# Generated by Django 5.2.5 on 2025-09-04 04:05

from django.db import migrations, models
import secrets
import string


def generate_prefix_ids_for_connections(apps, schema_editor):
    """Generate prefix_ids for existing Connection records"""
    Connection = apps.get_model('connections', 'Connection')
    
    def generate_prefix_id():
        chars = string.ascii_lowercase + string.digits
        random_string = ''.join(secrets.choice(chars) for _ in range(8))
        return f"con_{random_string}"
    
    # Generate unique prefix_ids for any existing connections
    for connection in Connection.objects.all():
        while True:
            prefix_id = generate_prefix_id()
            if not Connection.objects.filter(prefix_id=prefix_id).exists():
                connection.prefix_id = prefix_id
                connection.save()
                break
    
    print(f"Generated prefix_ids for {Connection.objects.count()} connections")


def reverse_prefix_ids(apps, schema_editor):
    """Reverse operation - clear prefix_ids"""
    Connection = apps.get_model('connections', 'Connection')
    Connection.objects.update(prefix_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='prefix_id',
            field=models.CharField(editable=False, max_length=50, unique=True, null=True),
        ),
        migrations.RunPython(
            generate_prefix_ids_for_connections,
            reverse_prefix_ids,
        ),
        migrations.AlterField(
            model_name='connection',
            name='prefix_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
