# Generated by Django 5.2.5 on 2025-09-04 04:28

from django.db import migrations
import secrets
import string


def copy_integrations_to_connections(apps, schema_editor):
    """Copy Integration records to Connection records with Provider foreign key updates"""
    
    # Get model references
    Integration = apps.get_model('integrations', 'Integration')
    IntegrationProvider = apps.get_model('integrations', 'IntegrationProvider')
    Connection = apps.get_model('connections', 'Connection')
    Provider = apps.get_model('connections', 'Provider')
    
    def generate_prefix_id():
        chars = string.ascii_lowercase + string.digits
        random_string = ''.join(secrets.choice(chars) for _ in range(8))
        return f"con_{random_string}"
    
    # Create mapping from IntegrationProvider to Provider
    provider_mapping = {}
    for int_provider in IntegrationProvider.objects.all():
        try:
            # Find matching Provider by name
            new_provider = Provider.objects.get(name=int_provider.name)
            provider_mapping[int_provider.id] = new_provider
        except Provider.DoesNotExist:
            print(f"Warning: No Provider found for IntegrationProvider '{int_provider.name}'")
            continue
    
    # Copy Integration records to Connection
    created_count = 0
    for integration in Integration.objects.all():
        if integration.provider_id not in provider_mapping:
            print(f"Skipping Integration {integration.id}: no Provider mapping for provider_id {integration.provider_id}")
            continue
        
        # Generate unique prefix_id
        while True:
            prefix_id = generate_prefix_id()
            if not Connection.objects.filter(prefix_id=prefix_id).exists():
                break
        
        # Create Connection record
        connection = Connection.objects.create(
            prefix_id=prefix_id,
            account=integration.account,
            created_by=integration.created_by,
            provider=provider_mapping[integration.provider_id],
            external_account_id=integration.external_account_id,
            external_account_name=integration.external_account_name,
            organization_name=integration.organization_name,
            status=integration.status,
            connected_at=integration.connected_at,
            last_sync_at=integration.last_sync_at,
            last_error=integration.last_error,
            config=integration.config,
            created_at=integration.created_at,
            updated_at=integration.updated_at
        )
        
        created_count += 1
        print(f"Copied Integration {integration.id} -> Connection {connection.id} ({connection.prefix_id})")
    
    print(f"Successfully copied {created_count} Integration records to Connection")


def reverse_copy_integrations(apps, schema_editor):
    """Reverse the data migration by deleting all Connection records"""
    Connection = apps.get_model('connections', 'Connection')
    count = Connection.objects.count()
    Connection.objects.all().delete()
    print(f"Deleted {count} Connection records")


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_auto_20250904_0405'),
        ('integrations', '0001_initial'),  # Ensure Integration model exists
    ]

    operations = [
        migrations.RunPython(
            copy_integrations_to_connections,
            reverse_copy_integrations,
        ),
    ]
