# Generated by Django 5.2.5 on 2025-09-04 05:54

from django.db import migrations


def copy_integrations_models_to_connections(apps, schema_editor):
    """Copy IntegrationCredential, OAuthState, and IntegrationSync to connections models"""
    
    # Get model references
    # Old models from integrations app
    Integration = apps.get_model('integrations', 'Integration')
    IntegrationCredential = apps.get_model('integrations', 'IntegrationCredential')
    OAuthState = apps.get_model('integrations', 'OAuthState')
    IntegrationSync = apps.get_model('integrations', 'IntegrationSync')
    
    # New models from connections app
    Connection = apps.get_model('connections', 'Connection')
    Credential = apps.get_model('connections', 'Credential')
    ConnectionOAuthState = apps.get_model('connections', 'OAuthState')
    Sync = apps.get_model('connections', 'Sync')
    
    # Create Integration -> Connection mapping for foreign key updates
    integration_to_connection_mapping = {}
    for integration in Integration.objects.all():
        try:
            # Find matching Connection by account + external_account_id
            connection = Connection.objects.get(
                account=integration.account,
                external_account_id=integration.external_account_id
            )
            integration_to_connection_mapping[integration.id] = connection
        except Connection.DoesNotExist:
            print(f"Warning: No Connection found for Integration {integration.id}")
            continue
    
    # 1. Copy IntegrationCredential -> Credential
    credential_count = 0
    for int_credential in IntegrationCredential.objects.all():
        if int_credential.integration_id not in integration_to_connection_mapping:
            print(f"Skipping IntegrationCredential {int_credential.id}: no Connection mapping")
            continue
        
        connection = integration_to_connection_mapping[int_credential.integration_id]
        
        # Create Credential record
        credential = Credential.objects.create(
            connection=connection,
            access_token=int_credential.access_token,
            refresh_token=int_credential.refresh_token or '',
            token_type=int_credential.token_type,
            expires_at=int_credential.expires_at,
            scopes=int_credential.scopes,
            additional_credentials=int_credential.additional_credentials,
            created_at=int_credential.created_at,
            updated_at=int_credential.updated_at,
            last_refreshed_at=int_credential.last_refreshed_at
        )
        
        credential_count += 1
        print(f"Copied IntegrationCredential {int_credential.id} -> Credential {credential.id}")
    
    print(f"Successfully copied {credential_count} credentials")
    
    # 2. Copy OAuthState -> OAuthState  
    oauth_count = 0
    for old_oauth in OAuthState.objects.all():
        if old_oauth.integration_id not in integration_to_connection_mapping:
            print(f"Skipping OAuthState {old_oauth.id}: no Connection mapping")
            continue
        
        connection = integration_to_connection_mapping[old_oauth.integration_id]
        
        # Create new OAuthState record
        new_oauth = ConnectionOAuthState.objects.create(
            connection=connection,
            state_token=old_oauth.state_token,
            created_by=old_oauth.created_by,
            is_used=old_oauth.is_used,
            used_at=old_oauth.used_at,
            created_at=old_oauth.created_at
        )
        
        oauth_count += 1
        print(f"Copied OAuthState {old_oauth.id} -> OAuthState {new_oauth.id}")
    
    print(f"Successfully copied {oauth_count} OAuth states")
    
    # 3. Copy IntegrationSync -> Sync
    sync_count = 0
    for int_sync in IntegrationSync.objects.all():
        if int_sync.integration_id not in integration_to_connection_mapping:
            print(f"Skipping IntegrationSync {int_sync.id}: no Connection mapping")
            continue
        
        connection = integration_to_connection_mapping[int_sync.integration_id]
        
        # Create Sync record
        sync = Sync.objects.create(
            connection=connection,
            sync_type=int_sync.sync_type,
            status=int_sync.status,
            records_processed=int_sync.records_processed,
            records_success=int_sync.records_success,
            records_failed=int_sync.records_failed,
            error_message=int_sync.error_message,
            error_details=int_sync.error_details,
            metadata=int_sync.metadata,
            started_at=int_sync.started_at,
            completed_at=int_sync.completed_at
        )
        
        sync_count += 1
        print(f"Copied IntegrationSync {int_sync.id} -> Sync {sync.id}")
    
    print(f"Successfully copied {sync_count} sync records")
    
    print(f"Total migration summary:")
    print(f"  - {credential_count} Credentials")
    print(f"  - {oauth_count} OAuth States") 
    print(f"  - {sync_count} Sync records")


def reverse_copy_integrations_models(apps, schema_editor):
    """Reverse the data migration by deleting all copied records"""
    Credential = apps.get_model('connections', 'Credential')
    ConnectionOAuthState = apps.get_model('connections', 'OAuthState')
    Sync = apps.get_model('connections', 'Sync')
    
    credential_count = Credential.objects.count()
    oauth_count = ConnectionOAuthState.objects.count()
    sync_count = Sync.objects.count()
    
    Credential.objects.all().delete()
    ConnectionOAuthState.objects.all().delete()
    Sync.objects.all().delete()
    
    print(f"Deleted {credential_count} credentials, {oauth_count} OAuth states, {sync_count} sync records")


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_add_credential_oauth_sync_models'),
        ('integrations', '0001_initial'),  # Ensure Integration models exist
    ]

    operations = [
        migrations.RunPython(
            copy_integrations_models_to_connections,
            reverse_copy_integrations_models,
        ),
    ]
