[pytest]
DJANGO_SETTINGS_MODULE = fafixed.settings
addopts = --cov=. --cov-report=html --cov-report=term --cov-fail-under=80 --tb=short
testpaths = */tests/
python_files = test_*.py
python_classes = Test*
python_functions = test_*