# Generated by Django 5.2.5 on 2025-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='customer', help_text='User role - difficult to change once set for security', max_length=20),
        ),
    ]
