# Generated by Django 5.2.5 on 2025-09-04 06:28

import django.db.models.deletion
import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0007_copy_integrations_models_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_transaction_id', models.CharField(db_index=True, max_length=255)),
                ('external_account_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('spend', 'Spend'), ('receive', 'Receive'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('authorised', 'Authorised'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending')], db_index=True, max_length=20)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('contact_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.URLField(blank=True, help_text='Direct link to view this transaction in Xero', max_length=500, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('prefix_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='connections.connection')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
            bases=(models.Model, shared.models.PrefixIdMixin),
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('external_line_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='financial_data.transaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['connection', 'date'], name='financial_d_connect_d03d85_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['connection', 'status'], name='financial_d_connect_283a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['connection', 'is_reconciled'], name='financial_d_connect_1c7099_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_account_id', 'date'], name='financial_d_externa_61cd5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('connection', 'external_transaction_id')},
        ),
    ]
