# Generated by Django 5.2.5 on 2025-09-04 06:28

from django.db import migrations
import secrets
import string


def copy_transactiondata_to_transaction(apps, schema_editor):
    """Copy TransactionData records to Transaction model with Connection foreign keys"""
    
    # Get model references
    TransactionData = apps.get_model('integrations', 'TransactionData')
    Integration = apps.get_model('integrations', 'Integration')
    Connection = apps.get_model('connections', 'Connection')
    Transaction = apps.get_model('financial_data', 'Transaction')
    TransactionLineItem = apps.get_model('integrations', 'TransactionLineItem')
    NewTransactionLineItem = apps.get_model('financial_data', 'TransactionLineItem')
    
    def generate_prefix_id():
        chars = string.ascii_lowercase + string.digits
        random_string = ''.join(secrets.choice(chars) for _ in range(8))
        return f"txn_{random_string}"
    
    # Create Integration → Connection mapping
    integration_to_connection_mapping = {}
    for integration in Integration.objects.all():
        try:
            # Find matching Connection by account + external_account_id
            connection = Connection.objects.get(
                account=integration.account,
                external_account_id=integration.external_account_id
            )
            integration_to_connection_mapping[integration.id] = connection
        except Connection.DoesNotExist:
            print(f"Warning: No Connection found for Integration {integration.id}")
            continue
    
    print(f"Created mapping for {len(integration_to_connection_mapping)} integrations")
    
    # Copy TransactionData → Transaction
    transaction_count = 0
    skipped_count = 0
    
    for transaction_data in TransactionData.objects.all():
        if transaction_data.integration_id not in integration_to_connection_mapping:
            print(f"Skipping TransactionData {transaction_data.id}: no Connection mapping")
            skipped_count += 1
            continue
        
        connection = integration_to_connection_mapping[transaction_data.integration_id]
        
        # Generate unique prefix_id
        while True:
            prefix_id = generate_prefix_id()
            if not Transaction.objects.filter(prefix_id=prefix_id).exists():
                break
        
        # Create Transaction record
        transaction = Transaction.objects.create(
            prefix_id=prefix_id,
            connection=connection,
            external_transaction_id=transaction_data.external_transaction_id,
            external_account_id=transaction_data.external_account_id,
            transaction_type=transaction_data.transaction_type,
            date=transaction_data.date,
            reference=transaction_data.reference,
            description=transaction_data.description,
            amount=transaction_data.amount,
            currency_code=transaction_data.currency_code,
            status=transaction_data.status,
            is_reconciled=transaction_data.is_reconciled,
            contact_name=transaction_data.contact_name,
            contact_external_id=transaction_data.contact_external_id,
            external_url=transaction_data.external_url,
            raw_data=transaction_data.raw_data,
            created_at=transaction_data.created_at,
            updated_at=transaction_data.updated_at,
            last_synced_at=transaction_data.last_synced_at
        )
        
        transaction_count += 1
        
        if transaction_count % 100 == 0:
            print(f"Copied {transaction_count} transactions...")
    
    print(f"Successfully copied {transaction_count} TransactionData records to Transaction")
    print(f"Skipped {skipped_count} records due to missing Connection mapping")
    
    # Copy TransactionLineItem → TransactionLineItem (if any exist)
    line_item_count = 0
    for old_line_item in TransactionLineItem.objects.all():
        # Find the corresponding new Transaction
        try:
            old_transaction_data = old_line_item.transaction
            if old_transaction_data.integration_id not in integration_to_connection_mapping:
                continue
                
            # Find matching new Transaction by external_transaction_id and connection
            connection = integration_to_connection_mapping[old_transaction_data.integration_id]
            new_transaction = Transaction.objects.get(
                connection=connection,
                external_transaction_id=old_transaction_data.external_transaction_id
            )
            
            # Create new TransactionLineItem
            NewTransactionLineItem.objects.create(
                transaction=new_transaction,
                description=old_line_item.description,
                quantity=old_line_item.quantity,
                unit_amount=old_line_item.unit_amount,
                line_amount=old_line_item.line_amount,
                tax_type=old_line_item.tax_type,
                tax_amount=old_line_item.tax_amount,
                account_code=old_line_item.account_code,
                account_name=old_line_item.account_name,
                external_line_item_id=old_line_item.external_line_item_id,
                raw_data=old_line_item.raw_data,
                created_at=old_line_item.created_at,
                updated_at=old_line_item.updated_at
            )
            
            line_item_count += 1
            
        except Exception as e:
            print(f"Error copying line item {old_line_item.id}: {e}")
            continue
    
    print(f"Successfully copied {line_item_count} TransactionLineItem records")
    
    print(f"Total migration summary:")
    print(f"  - {transaction_count} Transactions migrated")
    print(f"  - {line_item_count} Line Items migrated")
    print(f"  - {skipped_count} transactions skipped")


def reverse_copy_transactiondata(apps, schema_editor):
    """Reverse the data migration by deleting all Transaction records"""
    Transaction = apps.get_model('financial_data', 'Transaction')
    TransactionLineItem = apps.get_model('financial_data', 'TransactionLineItem')
    
    transaction_count = Transaction.objects.count()
    line_item_count = TransactionLineItem.objects.count()
    
    Transaction.objects.all().delete()  # Cascade will delete line items
    
    print(f"Deleted {transaction_count} transactions and {line_item_count} line items")


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0001_add_transaction_models'),
        ('connections', '0005_copy_integration_to_connection_data'),  # Need Connection data
        ('integrations', '0001_initial'),  # Need TransactionData
    ]

    operations = [
        migrations.RunPython(
            copy_transactiondata_to_transaction,
            reverse_copy_transactiondata,
        ),
    ]
