# Generated by Django 5.2.5 on 2025-09-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0002_copy_transactiondata_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlineitem',
            name='tracking_category_1_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='tracking_category_1_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='tracking_category_1_option',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='tracking_category_2_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='tracking_category_2_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='tracking_category_2_option',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
