# Generated by Django 5.2.5 on 2025-10-01 01:04

import django.db.models.deletion
import shared.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_role'),
        ('financial_data', '0004_add_accounting_models'),
        ('integrations', '0013_add_tracking_categories_to_transactionlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('fully_paid_on_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(default='AUD', max_length=3)),
                ('currency_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AUTHORISED', 'Authorised'), ('PAID', 'Paid'), ('VOIDED', 'Voided'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20)),
                ('has_attachments', models.BooleanField(default=False)),
                ('external_bill_id', models.CharField(max_length=255)),
                ('external_data', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='financial_data.contact')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
            bases=(models.Model, shared.models.PrefixIdMixin),
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('account_code', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('discount_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_type', models.CharField(blank=True, max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tracking_category_1_id', models.CharField(blank=True, max_length=255)),
                ('tracking_category_1_name', models.CharField(blank=True, max_length=200)),
                ('tracking_category_1_option', models.CharField(blank=True, max_length=200)),
                ('tracking_category_2_id', models.CharField(blank=True, max_length=255)),
                ('tracking_category_2_name', models.CharField(blank=True, max_length=200)),
                ('tracking_category_2_option', models.CharField(blank=True, max_length=200)),
                ('external_line_item_id', models.CharField(blank=True, max_length=255)),
                ('external_data', models.JSONField(default=dict)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('prefix_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('chart_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_line_items', to='financial_data.chartofaccountsentry')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='financial_data.purchasebill')),
            ],
            options={
                'ordering': ['line_number'],
            },
            bases=(models.Model, shared.models.PrefixIdMixin),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Reconciliation'), ('MATCHED', 'Matched to Invoice'), ('PARTIAL', 'Partial Payment'), ('OVERPAID', 'Overpayment'), ('UNMATCHED', 'No Invoice Match')], default='PENDING', max_length=20)),
                ('reconciliation_confidence', models.FloatField(default=0.0)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('external_payment_id', models.CharField(blank=True, max_length=255)),
                ('external_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial_data.salesinvoice')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='financial_data.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['integration', 'status'], name='financial_d_integra_93ebdc_idx'), models.Index(fields=['account', 'payment_date'], name='financial_d_account_af2837_idx'), models.Index(fields=['transaction'], name='financial_d_transac_879a30_idx'), models.Index(fields=['invoice'], name='financial_d_invoice_62b59e_idx')],
                'unique_together': {('integration', 'external_payment_id')},
            },
            bases=(models.Model, shared.models.PrefixIdMixin),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['integration', 'status'], name='financial_d_integra_2076b7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['integration', 'invoice_date'], name='financial_d_integra_25b8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['contact', 'status'], name='financial_d_contact_541404_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['account', 'status', 'due_date'], name='financial_d_account_38771e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasebill',
            unique_together={('integration', 'external_bill_id')},
        ),
        migrations.AddIndex(
            model_name='billlineitem',
            index=models.Index(fields=['bill', 'line_number'], name='financial_d_bill_id_21963c_idx'),
        ),
        migrations.AddIndex(
            model_name='billlineitem',
            index=models.Index(fields=['chart_account'], name='financial_d_chart_a_f06a4a_idx'),
        ),
    ]
