# Generated by Django 5.2.5 on 2025-09-09 05:49

import django.db.models.deletion
import shared.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0007_copy_integrations_models_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, help_text='Category based on validation rule name', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('affected_transactions', models.JSONField(blank=True, default=list)),
                ('issue_key', models.CharField(blank=True, db_index=True, help_text='Key for grouping similar issues within account+chart scope', max_length=64)),
                ('occurrence_ids', models.JSONField(blank=True, default=list, help_text='List of individual occurrence IDs')),
                ('latest_occurrence', models.JSONField(blank=True, default=dict, help_text='Most recent occurrence details')),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('prefix_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='connections.connection')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_data_quality_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
            bases=(models.Model, shared.models.PrefixIdMixin),
        ),
        migrations.CreateModel(
            name='IssueResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_type', models.CharField(choices=[('fixed', 'Fixed'), ('ignored', 'Ignored'), ('false_positive', 'False Positive'), ('bulk_action', 'Bulk Action')], max_length=20)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('occurrence_ids', models.JSONField(blank=True, default=list, help_text='Specific occurrence IDs resolved')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional resolution metadata')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='data_quality.issue')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('severity_override', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Rule-specific configuration parameters')),
                ('run_on_sync', models.BooleanField(default=True, help_text='Run this rule when sync completes')),
                ('run_scheduled', models.BooleanField(default=False, help_text='Run this rule on schedule')),
                ('schedule_frequency', models.CharField(blank=True, help_text='Cron-like schedule expression', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_configs', to='connections.connection')),
            ],
            options={
                'ordering': ['rule_name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rules', models.PositiveIntegerField(default=0)),
                ('rules_passed', models.PositiveIntegerField(default=0)),
                ('rules_failed', models.PositiveIntegerField(default=0)),
                ('issues_found', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='connections.connection')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completeness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accuracy_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('critical_issues', models.PositiveIntegerField(default=0)),
                ('high_issues', models.PositiveIntegerField(default=0)),
                ('medium_issues', models.PositiveIntegerField(default=0)),
                ('low_issues', models.PositiveIntegerField(default=0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('validated_transactions', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='connections.connection')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['connection', 'date'], name='data_qualit_connect_e77c96_idx'), models.Index(fields=['date', 'overall_score'], name='data_qualit_date_84573c_idx')],
                'unique_together': {('connection', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['connection', 'status'], name='data_qualit_connect_0f63e0_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['connection', 'severity'], name='data_qualit_connect_b156be_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category', 'status'], name='data_qualit_categor_db56f2_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['issue_key'], name='data_qualit_issue_k_c0c1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='issueresolution',
            index=models.Index(fields=['issue', 'resolution_type'], name='data_qualit_issue_i_71d904_idx'),
        ),
        migrations.AddIndex(
            model_name='issueresolution',
            index=models.Index(fields=['resolved_by', 'resolved_at'], name='data_qualit_resolve_0b6c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='validationruleconfig',
            index=models.Index(fields=['connection', 'is_enabled'], name='data_qualit_connect_d5efcf_idx'),
        ),
        migrations.AddIndex(
            model_name='validationruleconfig',
            index=models.Index(fields=['rule_name', 'is_enabled'], name='data_qualit_rule_na_849698_idx'),
        ),
        migrations.AddIndex(
            model_name='validationruleconfig',
            index=models.Index(fields=['run_on_sync'], name='data_qualit_run_on__7246a9_idx'),
        ),
        migrations.AddIndex(
            model_name='validationruleconfig',
            index=models.Index(fields=['run_scheduled'], name='data_qualit_run_sch_4c2c49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validationruleconfig',
            unique_together={('connection', 'rule_name')},
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['connection', 'status'], name='data_qualit_connect_980973_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['connection', 'started_at'], name='data_qualit_connect_ed0883_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['triggered_by', 'status'], name='data_qualit_trigger_a0ab75_idx'),
        ),
    ]
