# Generated by Django 5.2.5 on 2025-09-09 06:04

from django.db import migrations


def copy_issues_from_integrations(apps, schema_editor):
    """Copy Issue records from integrations app to data_quality app"""
    
    # Get model classes
    IntegrationsIssue = apps.get_model('integrations', 'Issue')
    DataQualityIssue = apps.get_model('data_quality', 'Issue')
    Connection = apps.get_model('connections', 'Connection')
    
    print("Starting Issue migration from integrations to data_quality...")
    
    issues_migrated = 0
    issues_skipped = 0
    
    for old_issue in IntegrationsIssue.objects.all():
        try:
            # Find the corresponding Connection
            integration = old_issue.integration
            connection = Connection.objects.get(
                account=integration.account,
                external_account_id=integration.external_account_id
            )
            
            # Generate prefix_id manually (since PrefixIdMixin doesn't work in migrations)
            import secrets
            import string
            chars = string.ascii_lowercase + string.digits
            prefix_id = f"iss_{''.join(secrets.choice(chars) for _ in range(8))}"
            
            # Ensure uniqueness
            while DataQualityIssue.objects.filter(prefix_id=prefix_id).exists():
                prefix_id = f"iss_{''.join(secrets.choice(chars) for _ in range(8))}"
            
            # Create new Issue in data_quality app
            new_issue = DataQualityIssue.objects.create(
                prefix_id=prefix_id,
                connection=connection,
                title=old_issue.title,
                description=old_issue.description,
                category=old_issue.category,
                severity=old_issue.severity,
                status=old_issue.status,
                first_seen=old_issue.first_seen,
                last_seen=old_issue.last_seen,
                count=old_issue.count,
                affected_transactions=old_issue.affected_transactions,
                issue_key=old_issue.issue_key,
                occurrence_ids=old_issue.occurrence_ids,
                latest_occurrence=old_issue.latest_occurrence,
                resolution_notes=old_issue.resolution_notes,
                resolved_by=old_issue.resolved_by,
                resolved_at=old_issue.resolved_at,
            )
            
            print(f"✅ Migrated Issue: {new_issue.title} (ID: {old_issue.id} -> {new_issue.id})")
            print(f"   Category: {new_issue.category}, Severity: {new_issue.severity}")
            print(f"   Connection: {connection.organization_name} ({connection.prefix_id})")
            issues_migrated += 1
            
        except Connection.DoesNotExist:
            print(f"❌ SKIPPED Issue {old_issue.id} - no matching Connection found")
            print(f"   Integration: {integration.organization_name}")
            print(f"   External Account: {integration.external_account_id}")
            issues_skipped += 1
        except Exception as e:
            print(f"❌ ERROR migrating Issue {old_issue.id}: {e}")
            issues_skipped += 1
    
    print(f"\n📊 Migration Summary:")
    print(f"   Issues migrated: {issues_migrated}")
    print(f"   Issues skipped: {issues_skipped}")
    print(f"   Total processed: {issues_migrated + issues_skipped}")


def reverse_copy_issues(apps, schema_editor):
    """Remove all Issues from data_quality app (reverse migration)"""
    DataQualityIssue = apps.get_model('data_quality', 'Issue')
    count = DataQualityIssue.objects.count()
    DataQualityIssue.objects.all().delete()
    print(f"Reverse migration: Deleted {count} Issue records from data_quality app")


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0001_initial'),
        ('connections', '0007_copy_integrations_models_data'),  # Ensure connections are migrated first
        ('integrations', '0012_remove_category_choices'),  # Ensure integrations models exist
    ]

    operations = [
        migrations.RunPython(copy_issues_from_integrations, reverse_copy_issues),
    ]
