# Generated by Django 5.2.5 on 2025-09-11 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_copy_integrations_models_data'),
        ('data_quality', '0002_copy_issues_from_integrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroTrackingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_category_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_categories', to='connections.connection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='XeroTrackingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_option_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='data_quality.xerotrackingcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='xerotrackingcategory',
            index=models.Index(fields=['connection', 'status'], name='data_qualit_connect_dfdd17_idx'),
        ),
        migrations.AddIndex(
            model_name='xerotrackingcategory',
            index=models.Index(fields=['xero_category_id'], name='data_qualit_xero_ca_cfadd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xerotrackingcategory',
            unique_together={('connection', 'xero_category_id')},
        ),
        migrations.AddIndex(
            model_name='xerotrackingoption',
            index=models.Index(fields=['category', 'status'], name='data_qualit_categor_d26f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='xerotrackingoption',
            index=models.Index(fields=['xero_option_id'], name='data_qualit_xero_op_fef95f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xerotrackingoption',
            unique_together={('category', 'xero_option_id')},
        ),
    ]
