# Generated by Django 5.2.5 on 2025-09-11 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_copy_integrations_models_data'),
        ('data_quality', '0003_xerotrackingcategory_xerotrackingoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(help_text='List of condition dictionaries with field, operator, value')),
                ('condition_logic', models.CharField(choices=[('ALL', 'All conditions must match'), ('ANY', 'Any condition can match')], default='ALL', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher numbers = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detection_rules', to='connections.connection')),
                ('suggested_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detection_rules', to='data_quality.xerotrackingcategory')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_transaction_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('transaction_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPLIED', 'Applied to Xero'), ('IGNORED', 'Ignored'), ('SUPERSEDED', 'Superseded by newer suggestion')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_suggestions', to='connections.connection')),
                ('detection_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='data_quality.categorydetectionrule')),
                ('suggested_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='data_quality.xerotrackingcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='categorydetectionrule',
            index=models.Index(fields=['connection', 'is_active'], name='data_qualit_connect_9aefde_idx'),
        ),
        migrations.AddIndex(
            model_name='categorydetectionrule',
            index=models.Index(fields=['connection', 'priority'], name='data_qualit_connect_3d0c72_idx'),
        ),
        migrations.AddIndex(
            model_name='categorydetectionrule',
            index=models.Index(fields=['suggested_category'], name='data_qualit_suggest_4c47ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorydetectionrule',
            unique_together={('connection', 'name')},
        ),
        migrations.AddIndex(
            model_name='categorysuggestion',
            index=models.Index(fields=['connection', 'status'], name='data_qualit_connect_4dc8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysuggestion',
            index=models.Index(fields=['xero_transaction_id'], name='data_qualit_xero_tr_7f44ec_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysuggestion',
            index=models.Index(fields=['status', 'created_at'], name='data_qualit_status_5060c5_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysuggestion',
            index=models.Index(fields=['detection_rule', 'status'], name='data_qualit_detecti_ff9431_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorysuggestion',
            unique_together={('detection_rule', 'xero_transaction_id')},
        ),
    ]
