# Generated by Django 5.2.5 on 2025-09-11 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0004_categorydetectionrule_categorysuggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetectionrule',
            name='applied_count',
            field=models.IntegerField(default=0, help_text='Number of suggestions that were applied by users'),
        ),
        migrations.AddField(
            model_name='categorydetectionrule',
            name='ignored_count',
            field=models.IntegerField(default=0, help_text='Number of suggestions that were ignored by users'),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorysuggestion',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
