# Generated by Django 5.2.5 on 2025-11-01 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0005_add_user_decision_tracking'),
        ('integrations', '0013_add_tracking_categories_to_transactionlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetectionrule',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detection_rules', to='integrations.integration'),
        ),
        migrations.AlterField(
            model_name='xerotrackingcategory',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_categories', to='integrations.integration'),
        ),
    ]
