# Generated by Django 5.2.5 on 2025-11-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0006_change_connection_to_integration'),
        ('integrations', '0013_add_tracking_categories_to_transactionlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysuggestion',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_suggestions', to='integrations.integration'),
        ),
        migrations.AlterField(
            model_name='dataqualitymetric',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_quality_metrics', to='integrations.integration'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_issues', to='integrations.integration'),
        ),
        migrations.AlterField(
            model_name='validationruleconfig',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_validation_configs', to='integrations.integration'),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_validation_runs', to='integrations.integration'),
        ),
    ]
