# Generated by Django 5.2.5 on 2025-08-22 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('xero', 'Xero')], default='xero', max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('duplicate_transactions', 'Duplicate Transactions'), ('missing_data', 'Missing Data'), ('inconsistent_categories', 'Inconsistent Categories'), ('date_anomalies', 'Date Anomalies'), ('amount_discrepancies', 'Amount Discrepancies'), ('tax_code_errors', 'Tax Code Errors')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('affected_transactions', models.JSONField(blank=True, default=list)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='integrations.integration')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
