# Generated by Django 5.2.5 on 2025-08-24 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('integrations', '0003_allow_multiple_xero_per_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('account', 'provider', 'external_account_id')},
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_transaction_id', models.CharField(db_index=True, max_length=255)),
                ('external_account_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('spend', 'Spend'), ('receive', 'Receive'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('authorised', 'Authorised'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending')], db_index=True, max_length=20)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('contact_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.URLField(blank=True, help_text='Direct link to view this transaction in Xero', max_length=500, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='integrations.integration')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('external_line_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='integrations.transactiondata')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['integration', 'date'], name='integration_integra_25541d_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['integration', 'status'], name='integration_integra_e1fe03_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['integration', 'is_reconciled'], name='integration_integra_ab8759_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondata',
            index=models.Index(fields=['external_account_id', 'date'], name='integration_externa_d0e5f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiondata',
            unique_together={('integration', 'external_transaction_id')},
        ),
    ]
