# Generated by Django 5.2.5 on 2025-08-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_add_oauth_state_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='prefix_id',
            field=models.CharField(default='temp_integration', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
