# Generated by Django 5.2.5 on 2025-08-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_integration_prefix_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('severity_override', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Override the default severity level for this rule', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_configs', to='integrations.integration')),
            ],
            options={
                'ordering': ['rule_name'],
                'unique_together': {('integration', 'rule_name')},
            },
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rules', models.PositiveIntegerField(default=0)),
                ('rules_passed', models.PositiveIntegerField(default=0)),
                ('rules_failed', models.PositiveIntegerField(default=0)),
                ('issues_found', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['integration', 'status'], name='integration_integra_b57480_idx'), models.Index(fields=['started_at'], name='integration_started_de49cb_idx')],
            },
        ),
    ]
