# Generated by Django 5.2.5 on 2025-08-27 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_add_validation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionValidationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('issues_found', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_statuses', to='integrations.transactiondata')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction', 'rule_name'], name='integration_transac_01e8b0_idx'), models.Index(fields=['status'], name='integration_status_12acca_idx'), models.Index(fields=['completed_at'], name='integration_complet_310946_idx')],
                'unique_together': {('transaction', 'rule_name')},
            },
        ),
    ]
