# Generated by Django 5.2.5 on 2025-08-31 23:11

from django.db import migrations, models
import secrets
import string


def generate_prefix_id(prefix='txn', length=8):
    """Generate a unique prefix_id"""
    chars = string.ascii_lowercase + string.digits
    random_string = ''.join(secrets.choice(chars) for _ in range(length))
    return f"{prefix}_{random_string}"


def populate_transaction_prefix_ids(apps, schema_editor):
    """Populate prefix_id for existing TransactionData records"""
    TransactionData = apps.get_model('integrations', 'TransactionData')
    
    for transaction in TransactionData.objects.filter(prefix_id__isnull=True):
        # Generate unique prefix_id
        while True:
            prefix_id = generate_prefix_id()
            if not TransactionData.objects.filter(prefix_id=prefix_id).exists():
                transaction.prefix_id = prefix_id
                transaction.save()
                break


def reverse_populate_transaction_prefix_ids(apps, schema_editor):
    """Reverse migration - set all prefix_ids to None"""
    TransactionData = apps.get_model('integrations', 'TransactionData')
    TransactionData.objects.update(prefix_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_transactionvalidationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='prefix_id',
            field=models.CharField(max_length=50, editable=False, null=True, blank=True),
        ),
        migrations.RunPython(
            populate_transaction_prefix_ids,
            reverse_populate_transaction_prefix_ids
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='prefix_id',
            field=models.CharField(max_length=50, unique=True, editable=False),
        ),
    ]
