# Generated by Django 5.2.5 on 2025-09-01 00:13

from django.db import migrations
from django.db import models
import secrets
import string


def generate_prefix_id(prefix='txn', length=8):
    """Generate a unique prefix_id"""
    chars = string.ascii_lowercase + string.digits
    random_string = ''.join(secrets.choice(chars) for _ in range(length))
    return f"{prefix}_{random_string}"


def populate_missing_prefix_ids(apps, schema_editor):
    """Populate prefix_id for ALL TransactionData records that don't have one"""
    TransactionData = apps.get_model('integrations', 'TransactionData')
    
    # Find all transactions without prefix_id
    transactions_without_prefix = TransactionData.objects.filter(
        models.Q(prefix_id__isnull=True) | models.Q(prefix_id='')
    )
    
    count = transactions_without_prefix.count()
    print(f"Found {count} transactions without prefix_id")
    
    if count == 0:
        print("All transactions already have prefix_ids")
        return
    
    updated_count = 0
    for transaction in transactions_without_prefix:
        # Generate unique prefix_id
        attempts = 0
        while attempts < 100:  # Safety limit
            prefix_id = generate_prefix_id()
            if not TransactionData.objects.filter(prefix_id=prefix_id).exists():
                transaction.prefix_id = prefix_id
                transaction.save(update_fields=['prefix_id'])
                updated_count += 1
                break
            attempts += 1
        
        if attempts >= 100:
            raise Exception(f"Could not generate unique prefix_id for transaction {transaction.id}")
    
    print(f"Successfully updated {updated_count} transactions with prefix_ids")


def reverse_populate_missing_prefix_ids(apps, schema_editor):
    """Reverse migration - don't actually remove prefix_ids as that would be destructive"""
    print("Reverse migration: No action taken to preserve data integrity")


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_add_transaction_prefix_id'),
    ]

    operations = [
        migrations.RunPython(
            populate_missing_prefix_ids,
            reverse_populate_missing_prefix_ids
        ),
    ]
