# Generated by Django 5.2.5 on 2025-09-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_add_issue_enhancements'),
        ('integrations', '0010_populate_missing_transaction_prefix_ids'),
    ]

    operations = [
    ]
