# Generated by Django 5.2.5 on 2025-09-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_merge_20250901_0412'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='issue',
            new_name='integration_integra_7cf5e0_idx',
            old_name='integrations_integration_status_category_idx',
        ),
        migrations.RenameIndex(
            model_name='issue',
            new_name='integration_issue_k_7303ab_idx',
            old_name='integrations_issue_key_idx',
        ),
        migrations.RenameIndex(
            model_name='issue',
            new_name='integration_integra_2e02c2_idx',
            old_name='integrations_integration_category_status_idx',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(db_index=True, help_text='Category based on validation rule name', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prefix_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
